name: CI

on:
  push:
    branches: [main, master]
    tags: '*'
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      # - uses: actions/checkout@v4

      # - name: Setup Python
      #   uses: actions/setup-python@v5
      #   with:
      #     python-version: ${{ matrix.python }}
      #     cache: 'pip'

      - name: Install tesseract
        run: sudo apt-get -y update && sudo apt-get install -y tesseract-ocr tesseract-ocr-fra

      - name: Print tesseract version
        run: echo $(tesseract --version)

      # - name: Test pytesseract package installation
      #   run: pip install -U . && pip show pytesseract && python -c 'import pytesseract'

  tests:
    needs: [setup]
    uses: asottile/workflows/.github/workflows/tox.yml@v1.6.0
    with:
      env: '["py39", "py310", "py311", "py312", "py313"]'
      os: ubuntu-latest
